// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByqxtKioORVHsFSRObuXiwQkiOCcIXCgQ',
    appId: '1:945025430217:web:1a2acb8e3b92bb05705318',
    messagingSenderId: '945025430217',
    projectId: 'testchat-a2b98',
    authDomain: 'testchat-a2b98.firebaseapp.com',
    storageBucket: 'testchat-a2b98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_D7O7uxWbchy9HOHEZCBIeSsyp0y-UA4',
    appId: '1:945025430217:android:9772ec85d755daca705318',
    messagingSenderId: '945025430217',
    projectId: 'testchat-a2b98',
    storageBucket: 'testchat-a2b98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7lPXiKkthKq4XZxIATv9tOAJZXmASYlk',
    appId: '1:945025430217:ios:37a6076ce4de46b2705318',
    messagingSenderId: '945025430217',
    projectId: 'testchat-a2b98',
    storageBucket: 'testchat-a2b98.appspot.com',
    iosBundleId: 'com.example.chatAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7lPXiKkthKq4XZxIATv9tOAJZXmASYlk',
    appId: '1:945025430217:ios:37a6076ce4de46b2705318',
    messagingSenderId: '945025430217',
    projectId: 'testchat-a2b98',
    storageBucket: 'testchat-a2b98.appspot.com',
    iosBundleId: 'com.example.chatAppTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByqxtKioORVHsFSRObuXiwQkiOCcIXCgQ',
    appId: '1:945025430217:web:4ea0556a319513cd705318',
    messagingSenderId: '945025430217',
    projectId: 'testchat-a2b98',
    authDomain: 'testchat-a2b98.firebaseapp.com',
    storageBucket: 'testchat-a2b98.appspot.com',
  );
}
